# Generated by Django 3.1.7 on 2021-04-29 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PositionEnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PositionStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrainName', models.CharField(max_length=100)),
                ('TrainNo', models.CharField(max_length=14)),
                ('End', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traincrud.positionend')),
                ('Start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traincrud.positionstart')),
            ],
        ),
    ]
