# Generated by Django 3.1.7 on 2021-04-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traincrud', '0002_auto_20210429_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='dateoflauch',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
