# Generated by Django 3.1.7 on 2021-04-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traincrud', '0003_auto_20210429_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='train_image',
            new_name='Train_image',
        ),
    ]
