# Generated by Django 3.1.7 on 2021-04-29 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traincrud', '0004_auto_20210429_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='Train_image',
            new_name='TrainImage',
        ),
    ]
