# Generated by Django 3.1.7 on 2021-04-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traincrud', '0005_auto_20210429_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='TrainImage',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
