# Generated by Django 3.1.7 on 2021-04-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traincrud', '0007_auto_20210429_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='TrainImage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
