# Generated by Django 3.1.7 on 2021-11-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traincrud', '0010_auto_20210430_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='End',
        ),
        migrations.RemoveField(
            model_name='train',
            name='Goods',
        ),
        migrations.RemoveField(
            model_name='train',
            name='Passenger',
        ),
        migrations.RemoveField(
            model_name='train',
            name='Start',
        ),
        migrations.RemoveField(
            model_name='train',
            name='TrainName',
        ),
        migrations.RemoveField(
            model_name='train',
            name='TrainNo',
        ),
        migrations.RemoveField(
            model_name='train',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='train',
            name='dateoflauch',
        ),
        migrations.DeleteModel(
            name='PositionEnd',
        ),
        migrations.DeleteModel(
            name='PositionStart',
        ),
    ]
