# Generated by Django 3.2.9 on 2021-11-17 20:40

from django.db import migrations, models
import traincrud.validators


class Migration(migrations.Migration):

    dependencies = [
        ('traincrud', '0012_train_outputimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video/', validators=[traincrud.validators.file_size])),
            ],
        ),
    ]
