# Generated by Django 3.2.9 on 2021-11-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traincrud', '0013_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='OutputVideo',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
