# Generated by Django 3.2.9 on 2021-12-04 15:07

from django.db import migrations, models
import humancounter.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrainImage', models.ImageField(upload_to='images/')),
                ('OutputImage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video/', validators=[humancounter.validators.file_size])),
                ('OutputVideo', models.CharField(max_length=100)),
            ],
        ),
    ]
