# Generated by Django 3.1.7 on 2021-04-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traincrud', '0006_auto_20210429_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='TrainImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
