# Generated by Django 3.1.7 on 2021-04-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traincrud', '0009_auto_20210430_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='TrainImage',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
