# Generated by Django 3.2.6 on 2021-11-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traincrud', '0011_auto_20211115_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='OutputImage',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
